# @package habitat.dataset
defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_

type: DDNPlusNav-v1
split: train
data_path: data/datasets/ddnplus/hssd-hab_v0.2.5/{split}/{split}.json
scenes_dir: data/scene_datasets/hssd-hab/scenes